### ISSUE TITLE
Email not received

### ISSUE THREAD

**Issue by sajidanower23** [thundergolfer/automated-github-organization-invites#3]
After deploying, I put in a valid username and it said 'OK, check your email.' 
When I log into the organization, I can see that an invitation to the said user is pending, which means the invitation for sent. However, I did not receive any email. 
Any idea why this might be happening?
Thanks

**Comment by thundergolfer** [comment]
Sorry for late response. 

Were you already a member of the organisation? Like, were you using 2 different accounts to test this, one with membership and one without?

**Comment by sajidanower23** [comment]
Hey,
No, the account the email was linked to was not a member of the organisation.
It just worked when I tried again though.

We were using this for adding students to a class organisation. We had some (around 5 out of 500) students reporting that they did not get an email either.

Perhaps something to do with Heroku?

**Comment by thundergolfer** [comment]
Yes I think you're likely right that it's something to do with Heroku and their free tier. Worth me looking into though, so I'll keep the issue open. 

Thanks for the report.

**Comment by thundergolfer** [comment]
Closing due to general inactivity.
