### ISSUE TITLE
Remove Bootstrap from the project. 

### ISSUE THREAD

**Issue by haxzie-xx** [thundergolfer/automated-github-organization-invites#4]
I think it's a little overkill to use bootstrap in this project, since the design is minimal and removing bootstrap and using some bare minimum CSS and JS will help load the site faster. Can I work on it?

**Comment by thundergolfer** [comment]
Sorry for the late reply. I think you're right and I'd be happy to accept a PR 🙂

**Comment by thundergolfer** [comment]
Finally merged!
